version: "3.9"
services:
  mysqldb:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_HOST="%"
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hunted_api_db
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
  hunted-api:
    container_name: api
    build: ./
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysqldb
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: 
      - mysqldb